require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Mouthfeel' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'MouthfeelTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
end

target 'Mouthfeel-tvOS' do
  # Pods for Raven-tvOS

  target 'Mouthfeel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
