name: Build iOS adhoc

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-ios-adhoc:
    runs-on: macOS-latest
    steps:
      - name: Getting the repo
        uses: actions/checkout@v2
        
      - name: Installing node
        uses: actions/setup-node@master
        
      - name: Install node modules
        run: |
          npm install
          
      - name: Building bundle
        run: |
          npm react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Update build number
        run: |
          cd ios
          agvtool new-marketing-version 1.0.0
          agvtool new-version -all ${{github.run_number}}
      - name: Build ios
        uses: yukiarrr/ios-build-action@v1.3.2
        with:
          project-path: ios/Mouthfeelv2.xcodeproj
          workspace-path: ios/Mouthfeelv2.xcworkspace
          team-id: ${{ secrets.TEAM_ID }}
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.AD_HOC_MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.AD_HOC_CODE_SIGNING_IDENTITY }}
          export-method: ad-hoc
          output-path: output/output.ipa
          update-targets: Mouthfeelv2
          scheme: Mouthfeelv2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: output/output.ipa
